"""add origin and destination coordinates to shipments

Revision ID: 105b70ab3102
Revises: 707a3fac1691
Create Date: 2026-09-06 12:27:12.308369

"""
from alembic import op
import sqlalchemy as sa


revision = '105b70ab3102'
down_revision = '707a3fac1691'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('origin_latitude', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('origin_longitude', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('destination_latitude', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('destination_longitude', sa.Float(), nullable=True))
    op.drop_column('shipments', 'latitude')
    op.drop_column('shipments', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('shipments', 'destination_longitude')
    op.drop_column('shipments', 'destination_latitude')
    op.drop_column('shipments', 'origin_longitude')
    op.drop_column('shipments', 'origin_latitude')
    # ### end Alembic commands ###
