"""add ml fields to shipments

Revision ID: 707a3fac1691
Revises: 709ef54f0dea
Create Date: 2026-09-06 12:01:05.963875

"""
from alembic import op
import sqlalchemy as sa


revision = '707a3fac1691'
down_revision = '709ef54f0dea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('temperature_c', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('transit_duration_hr', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('pressure_psi', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('baseline_loss_pct', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('quantity_kg', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('spoilage_probability', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('risk_tier', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('spoil_prediction', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'spoil_prediction')
    op.drop_column('shipments', 'risk_tier')
    op.drop_column('shipments', 'spoilage_probability')
    op.drop_column('shipments', 'quantity_kg')
    op.drop_column('shipments', 'baseline_loss_pct')
    op.drop_column('shipments', 'pressure_psi')
    op.drop_column('shipments', 'transit_duration_hr')
    op.drop_column('shipments', 'temperature_c')
    op.drop_column('shipments', 'longitude')
    op.drop_column('shipments', 'latitude')
    # ### end Alembic commands ###
